(progn
 (defun print java:com.googlecode.linkedlisp.functions.Print)
 (defun write-line java:com.googlecode.linkedlisp.functions.WriteLine)
 (defun cons  java:com.googlecode.linkedlisp.functions.Cons)
 (defun cdr  java:com.googlecode.linkedlisp.functions.Cdr)
 (defun car  java:com.googlecode.linkedlisp.functions.Car)
 (defun append  java:com.googlecode.linkedlisp.functions.Cons)
 (defun rest  java:com.googlecode.linkedlisp.functions.Cdr)
 (defun first  java:com.googlecode.linkedlisp.functions.Car)
 (defun list  java:com.googlecode.linkedlisp.functions.ListFunction)
 (defun QUOTE  java:com.googlecode.linkedlisp.functions.Quote)
)