(progn
 (defun print java:com.googlecode.linkedlisp.functions.Print)
 (defun write-line java:com.googlecode.linkedlisp.functions.WriteLine)
 (defun cons  java:com.googlecode.linkedlisp.functions.Cons)
 (defun cdr  java:com.googlecode.linkedlisp.functions.Cdr)
 (defun car  java:com.googlecode.linkedlisp.functions.Car)
 (defun append  java:com.googlecode.linkedlisp.functions.Cons)
 (defun rest  java:com.googlecode.linkedlisp.functions.Cdr)
 (defun first  java:com.googlecode.linkedlisp.functions.Car)
 (defun concatenate  java:com.googlecode.linkedlisp.functions.Concatenate)
 (defun if  java:com.googlecode.linkedlisp.functions.If)
 (defun QUOTE  java:com.googlecode.linkedlisp.functions.Quote)
 (defun get  java:com.googlecode.linkedlisp.functions.Get)
 (defun set  java:com.googlecode.linkedlisp.functions.Set)
 (defun load  java:com.googlecode.linkedlisp.functions.Load)
 (defun prefix  java:com.googlecode.linkedlisp.functions.Prefix)
 (defun new  java:com.googlecode.linkedlisp.functions.New)
)