(progn
 (defun print java:com.googlecode.linkedlisp.functions.Print)
 (defun write-line java:com.googlecode.linkedlisp.functions.WriteLine)
 (defun cons  java:com.googlecode.linkedlisp.functions.Cons)
 (defun cdr  java:com.googlecode.linkedlisp.functions.Cdr)
 (defun car  java:com.googlecode.linkedlisp.functions.Car)
 (defun append  java:com.googlecode.linkedlisp.functions.Cons)
 (defun rest  java:com.googlecode.linkedlisp.functions.Cdr)
 (defun first  java:com.googlecode.linkedlisp.functions.Car)
 (defun last  java:com.googlecode.linkedlisp.functions.Last)
 (defun concatenate  java:com.googlecode.linkedlisp.functions.Concatenate)
 (defun if  java:com.googlecode.linkedlisp.functions.If)
 (defun QUOTE  java:com.googlecode.linkedlisp.functions.Quote)
 (defun get  java:com.googlecode.linkedlisp.functions.Get)
 (defun find  java:com.googlecode.linkedlisp.functions.Find)
 (defun set  java:com.googlecode.linkedlisp.functions.Set)
 (defun new  java:com.googlecode.linkedlisp.functions.New)
 (defun unset  java:com.googlecode.linkedlisp.functions.UnSet)
 (defun load  java:com.googlecode.linkedlisp.functions.Load)
 (defun prefix  java:com.googlecode.linkedlisp.functions.Prefix)
 (defun builtin  java:com.googlecode.linkedlisp.functions.Builtin)
 (defun rule  java:com.googlecode.linkedlisp.functions.Rule)
 (defun bind  java:com.googlecode.linkedlisp.functions.Bind)
 (defun seq  java:com.googlecode.linkedlisp.functions.Seq)
 (defun lambda  java:com.googlecode.linkedlisp.functions.Lambda)
 (defun let  java:com.googlecode.linkedlisp.functions.Let)

 (defun split  java:com.googlecode.linkedlisp.functions.Split)
 (defun replace  java:com.googlecode.linkedlisp.functions.Replace)
 (defun regex  java:com.googlecode.linkedlisp.functions.Replace)

 (defun + java:com.googlecode.linkedlisp.functions.Plus)
 (defun - java:com.googlecode.linkedlisp.functions.Minus)
 (defun / java:com.googlecode.linkedlisp.functions.Divide)
 (defun * java:com.googlecode.linkedlisp.functions.Multiply)
 (defun % java:com.googlecode.linkedlisp.functions.Mod)
 
 (defun and java:com.googlecode.linkedlisp.functions.And)
 (defun or  java:com.googlecode.linkedlisp.functions.Or)
 (defun not java:com.googlecode.linkedlisp.functions.Not)

 (defun = java:com.googlecode.linkedlisp.functions.Equal)

 (defun loop java:com.googlecode.linkedlisp.functions.Loop)

 (defun setf java:com.googlecode.linkedlisp.functions.Setf)
)
